# Generated by Django 4.2.2 on 2023-08-03 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('registration_start_date', models.DateField()),
                ('registration_end_date', models.DateField()),
                ('round1_date', models.DateField()),
                ('round2_date', models.DateField()),
                ('round3_date', models.DateField()),
                ('rules_and_guidelines', models.TextField()),
                ('organizers', models.TextField()),
                ('announcements', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_leader_name', models.CharField(max_length=100)),
                ('team_name', models.CharField(max_length=100)),
                ('team_leader_email', models.EmailField(max_length=254)),
                ('team_leader_phone', models.CharField(max_length=20)),
                ('team_leader_department', models.CharField(max_length=100)),
                ('team_leader_current_year', models.CharField(max_length=10)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.hackathon')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=100)),
                ('member_department', models.CharField(max_length=100)),
                ('member_phone', models.CharField(max_length=20)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.team')),
            ],
        ),
    ]
