# Generated by Django 4.2.2 on 2023-08-03 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamMember',
            new_name='Members',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_leader_current_year',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_leader_department',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_leader_email',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_leader_name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_leader_phone',
        ),
    ]
