# Generated by Django 4.2.2 on 2023-08-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0003_members_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='member_register_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
