# Generated by Django 4.2.2 on 2023-08-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0005_remove_hackathon_announcements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='member_email',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='members',
            name='member_phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='members',
            name='member_register_number',
            field=models.CharField(max_length=50),
        ),
    ]
